### ISSUE TITLE
First Release

### ISSUE THREAD

**Issue by psygo** [FanaroEngineering/fanaro_sabaki_theme_collection#8]
I hadn't really released things actually...

**Comment by JamesMowery** [comment]
Love it! If I could offer a suggestion. For the Fire and Ice theme, the coordinates are very hard to read. Maybe a bit more contrast would help. Would also love to see some more dark themes with some slightly more traditional stones. But this is an amazing start!

**Comment by psygo** [comment]
> the coordinates are very hard to read. Maybe a bit more contrast would help.

I haven't yet found a way of changing the colors of the coordinates nor the grid, as far as I remember. I ended up creating [this issue](https://github.com/SabakiHQ/Sabaki/issues/789) to get help with it, but no response so far &mdash; either I change the background, or the grid, or the coordinates, for more contrast.

(I thought I had this issue closed already, after the release had been done.)
